import copy
import re
from pathlib import Path
from typing import Any

from moonshot.src.connectors.connector import Connector
from moonshot.src.connectors.connector_prompt_arguments import ConnectorPromptArguments
from moonshot.src.connectors_endpoints.connector_endpoint import ConnectorEndpoint
from moonshot.src.metrics.metric_interface import MetricInterface
from moonshot.src.utils.timeit import timeit

DEFAULT_EVALUATION_MODEL = "openai-gpt4o"


class JointTesting2(MetricInterface):
    llm_prompt_template = """"""



    # Define your sample metric metadata such as the id, name, description
    # id should be something that is slugifed, eg. without spaces
    # metric_config will provide you the configuration configured in metrics_config.json
    def __init__(self):
        self.id = Path(__file__).stem
        self.name = "Agentic Joint Testing July"
        self.description = (
            "Joint testing work for july, will be updated lere for more info"
        )
        self.metric_config = self.get_metrics_configuration(self.id)
        self.endpoints = self.metric_config.get("endpoints", [DEFAULT_EVALUATION_MODEL])
        self.configurations = self.metric_config.get("configurations", {})

    # Timeit is a decorator that allows you to see how much time it is needed to run this method.
    # @timeit
    # This method will return some information about your metric when it is being invoked.
    # In this case, we should minimally return id, name, and description.
    def get_metadata(self) -> dict | None:
        """
        Retrieves and returns the metadata of the JointTesting class.

        Returns:
            dict | None: A dictionary containing the 'id', 'name', 'description', 'endpoints' and 'configurations' of
            the JointTesting class, or None if not applicable.
        """
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "endpoints": self.endpoints,
            "configurations": self.configurations,
        }


    # Timeit is a decorator that allows you to see how much time it is needed to run this method.
    @timeit
    async def get_results(
        self, prompts: Any, predicted_results: Any, targets: Any, *args, **kwargs
    ) -> dict:
        """
        Calculate and return the results.

        Parameters:
            prompts (Any): The prompts used for generating the predicted results.
            predicted_results (Any): The predicted results generated by the model.
            targets (Any): The target results for comparison.
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.

        Returns:
            dict: A dictionary containing my results
        """
        return {}